// فك Base64
let content = Buffer.from($json["data"], 'base64').toString('utf8');

// تعديل الـ image tag فقط
content = content.replace(/(image:\s*mazenmostafa429\/frontend)(:\S+)?/, "$1:" + $json["tag"]);

// رجّع الملف ل Base64 تاني
return [{ 
    json: { }, 
    binary: { 
        data: { 
            data: Buffer.from(content, 'utf8').toString('base64'), 
            mimeType: 'application/octet-stream', 
            fileName: 'deployment.yaml'
        } 
    } 
}];
